import { createFileRoute } from "@tanstack/react-router";

import { Link } from "@tanstack/react-router";

import { Button } from "@/components/ui/button";
import { IdCardsTablePage } from "@/pages/shared/IdCardsTablePage";

function RouteComponent() {
  return (
    <IdCardsTablePage
      title="ID cards"
      description="Student photo ID cards generated by your school."
      schoolId="sch_001"
      actions={
        <Button asChild>
          <Link to="/school/id-cards/create">Generate ID card</Link>
        </Button>
      }
    />
  );
}

export const Route = createFileRoute("/school/id-cards")({
  head: () => ({
    meta: [
      { title: "ID Cards — IDSuite School Portal" },
      { name: "description", content: "Student photo ID cards generated by your school, with status and design used." },
      { property: "og:title", content: "ID Cards — IDSuite School Portal" },
      { property: "og:description", content: "Student photo ID cards generated by your school, with status and design used." },
    ],
  }),
  component: RouteComponent,
});
