import { useQuery } from "@tanstack/react-query";

import { Card } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { MockDataNotice, PageHeader, StatusBadge } from "@/components/common/ui-kit";
import { idCardsService } from "@/services";
import { formatDateTime } from "@/utils/format";

export function IdCardsTablePage({
  title,
  description,
  schoolId,
  showSchoolColumn = false,
  actions,
}: {
  title: string;
  description: string;
  schoolId?: string;
  showSchoolColumn?: boolean;
  actions?: React.ReactNode;
}) {
  const { data } = useQuery({
    queryKey: ["id-cards", schoolId ?? "all"],
    queryFn: () => idCardsService.list(schoolId ? { schoolId } : undefined),
  });

  return (
    <>
      <PageHeader title={title} description={description} actions={actions} />
      <MockDataNotice />
      <Card className="overflow-hidden p-0">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Student</TableHead>
                <TableHead>Class</TableHead>
                <TableHead>Roll no.</TableHead>
                <TableHead>Design</TableHead>
                {showSchoolColumn ? <TableHead>School</TableHead> : null}
                <TableHead>Status</TableHead>
                <TableHead>Generated by</TableHead>
                <TableHead>When</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {(data ?? []).map((card) => (
                <TableRow key={card.id}>
                  <TableCell className="font-medium">{card.studentName}</TableCell>
                  <TableCell>{card.studentClass}</TableCell>
                  <TableCell className="text-muted-foreground">{card.rollNumber}</TableCell>
                  <TableCell>{card.designName}</TableCell>
                  {showSchoolColumn ? <TableCell>{card.schoolName}</TableCell> : null}
                  <TableCell>
                    <StatusBadge status={card.status} />
                  </TableCell>
                  <TableCell>{card.generatedBy}</TableCell>
                  <TableCell className="text-muted-foreground">
                    {formatDateTime(card.generatedAt)}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </Card>
    </>
  );
}
